#!/bin/sh
# prerm script for plymouth-jeiks-theme

set -e

case "$1" in
    remove|upgrade|deconfigure)
        update-alternatives --remove default.plymouth \
            /usr/share/plymouth/themes/different-tux/different-tux.plymouth || true
        update-initramfs -u
    ;;

    failed-upgrade)
        update-alternatives --install \
            /usr/share/plymouth/themes/default.plymouth default.plymouth \
            /usr/share/plymouth/themes/different-tux/different-tux.plymouth 200 || true
        update-initramfs -u
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
